version: "3"
services:
  neo4j:
    container_name: NRMS
    image: neo4j:5.12.0
    user: "${HOST_UID}:${HOST_GID}"
    volumes:
      - ./data:/data
      - ./plugins:/plugins
      - ./import:/import
      - ./conf:/conf
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*,algo.*
      - NEO4J_server_memory_heap_initial__size=512m
      - NEO4J_server_memory_heap_max__size=2G
      - NEO4J_apoc_uuid_enabled=true
      - NEO4J_server_default__listen__address=0.0.0.0
      - NEO4J_initial_dbms_default__database=neo4j
      - NEO4J_AUTH=neo4j/${NEO4J_PASSWORD}
    networks: 
      - nrms-app-network
    restart: unless-stopped

networks: 
  nrms-app-network: {}

volumes:
  nrms-app-volume: {}
